# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: deps:node:.
version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current

    steps:
      - checkout

      # Étapes pour construire l'image Docker
      - run:
          name: Update and install curl
          command: |
            sudo apt update && sudo apt upgrade && sudo apt install curl

      - run:
          name: Build Docker image
          command: |
            docker build -t niels2 .

      # Étapes pour exécuter les tests
      - run:
          name: Run tests and curl
          command: |
            docker run -d -p 8080:8080 niels2
            sleep 10
            curl http://127.0.0.1:8080


      - run:
          name: connection
          command: |
            echo "$DOCKERPASS" | docker login -u Kent1-DR --password-stdin

      - run:
          name: connection
          command: |
            docker tag niels2 "Kent1-DR/node-js-sample" && docker push "Kent1-DR/node-js-sample"


# Orchestrate our job run sequence
workflows:
  build:
    jobs:
      - build


